#!/usr/bin/env bash
#Bash script that transfers a file from our client to the server
# Accept 4 parameters
#	The path to the file to be transfered
#	The IP of the server we want to transfer the file to
#	The username scp connects with
#	The path to the SSH private key that scp uses

#File_path=$1
#server_IP=$2
#username=$3
#ssh_key=$4

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
