#!/usr/bin/env bash
# fixes a web server to run Ngix as the ngix user listening on all IPs on PORT 8080
# change user to ngix
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
#replace all listening port 80 to port 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# change ownership to read and write
chmod 644 /etc/nginx/nginx.conf
# destroy apache
pkill apache2
# restart service as user nginx
sudo -u nginx service nginx start
